# Generated by Django 4.1.3 on 2022-11-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_goals_alter_todo_ideas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complted',
            field=models.BooleanField(blank=True),
        ),
    ]
