# Generated by Django 4.1.3 on 2022-11-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_complted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complted',
            field=models.BooleanField(null=True),
        ),
    ]
